## Importing the neccessary libraries

## Data Collection and Preprossing

In [8]:
# print the 5 first rows of the data

heart_data.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3,0
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3,0
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3,0
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3,0
4,62,0,0,138,294,1,1,106,0,1.9,1,3,2,0

In [10]:
# no of rows and columns of the data

heart_data.shape

(1025, 14)

In [12]:
# checking some missing values

heart_data.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [14]:
# checking the distribution of Target variable

heart_data['target'].value_counts()

target
1    526
0    499
Name: count, dtype: int64

Splitting the fetaures and target

      --> targert column is the target
      --> all others column are feature

In [16]:
print(X)

      age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0      52    1   0       125   212    0        1      168      0      1.0
1      53    1   0       140   203    1        0      155      1      3.1
2      70    1   0       145   174    0        1      125      1      2.6
3      61    1   0       148   203    0        1      161      0      0.0
4      62    0   0       138   294    1        1      106      0      1.9
...   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...
1020   59    1   1       140   221    0        1      164      1      0.0
1021   60    1   0       125   258    0        0      141      1      2.8
1022   47    1   0       110   275    0        0      118      1      1.0
1023   50    0   0       110   254    0        0      159      0      0.0
1024   54    1   0       120   188    0        1      113      0      1.4

      slope  ca  thal
0         2   2     3
1         0   0     3
2         0   0     3
3         2   1     3
4         1   3     2
...     ...  ..   ...
1020      2   0     2
1021      1   1     3
1022      1   1     2
1023      2   0     2
1024      1   1     3

[1025 rows x 13 columns]

In [21]:
#scaling :- it use to
scaler = StandardScaler()
x_scaled = scaler.fit_transform(X)

In [22]:
X_train, X_test, Y_train, Y_test = train_test_split(
    X, Y, test_size=0.2,stratify=Y, random_state=42
)

Model Training

In [24]:
model = LogisticRegression()

**Model Evaluation**

Accuracy Score

In [27]:
print("Accuracy on Training data : ", training_data_accuracy)

Accuracy on Training data :  0.8475609756097561

In [29]:
print("Accuracy on Test data : ", test_data_accuracy)

Accuracy on Test data :  0.8341463414634146

In [30]:
input_data = (55,0,1,132,342,0,1,166,0,1.2,2,0,2,)

# change the input data to a numpy array

input_data_as_numpy_array = np.asarray(input_data)

# reshape the numpy array as we are predicting for only on instance

input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)

prediction = model.predict(input_data_reshaped)
print(prediction)

if (prediction[0]== 0):
  print("The Person does not have a Heart Disease")
else:
  print("The Person has Heart Disease")

[1]
The Person has Heart Disease

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(